spring.datasource.url=jdbc:mysql://mysql-todolist3dm-silasprata23-d7f1.c.aivencloud.com:23279/ecommerce?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_gQ1FucFTxyjtvnS4L5r
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
